### ISSUE TITLE
Add ononoki.org

### ISSUE THREAD

**Issue by ononoki1** [nkoehring/250kb-club#238]
```yaml
domain: ononoki.org
url: https://ononoki.org/
size: 54.5 KB compressed, 93.8 KB uncompressed
```

You can see the size on `Waterfall` section in [GTmetrix report](https://gtmetrix.com/reports/ononoki.org/HuBwSAR6/).
